version: "3.7"

services:
  db:
    build: ./db
    container_name: castillo_casa-db
    env_file:
      - ./db/.env
    image: castillo_casa-db:1.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3
    networks:
      castillo_casa-network:
        aliases:
          - castillo_casa-db
    ports:
      - "40000:3306"
      - "40001:33060"
    volumes:
      - type: volume
        source: castillo_casa-db-volume
        target: /data/mysql


networks:
  castillo_casa-network:
    driver: bridge
    ipam:
      config:
        - subnet: 168.10.10.0/24
    name: castillo_casa-network

volumes:
  castillo_casa-db-volume:
    name: castillo_casa-db-volume
